"""add is_admin to user

Revision ID: e0daa4bbc0ad
Revises: 20260424_0004
Create Date: 2026-05-30 17:25:41.963806
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e0daa4bbc0ad'
down_revision: Union[str, None] = '20260424_0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
